
package shoppingcartapplication_main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

public class InvoicePage 
{
 
        /**
         * This method displays the Invoice generated by the generateSummary method in the ShoppingCart class along with options to logout and go back to homepage.
         */
         
        public void display(ShoppingCart aCart)
        {
        
            cart = aCart;
            
        JFrame frame = new JFrame("Invoice");
        frame.setSize(1000,700);
        
        JPanel topPanel = new JPanel();
        topPanel.setLayout(new FlowLayout());
        
        JLabel productTitle = new JLabel("\t\tThank you for shopping!");
        productTitle.setFont(productTitle.getFont().deriveFont(40.0f));
        
        JButton logout = new JButton("Logout");
        logout.setPreferredSize(new Dimension(100,30));
        logout.setFont(logout.getFont().deriveFont(12.0f));
        JButton back = new JButton("Back to Homepage");
        back.setPreferredSize(new Dimension(150,30));
        back.setFont(back.getFont().deriveFont(12.0f));
        
        topPanel.add(productTitle);
        topPanel.add(Box.createRigidArea(new Dimension(200,0)));
        topPanel.add(back);
        topPanel.add(logout);

        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        
        JScrollPane scroll = new JScrollPane();
        
        JTextArea invoice = new JTextArea(cart.generateSummary());
        invoice.setFont(invoice.getFont().deriveFont(20.0f));
        scroll.add(invoice);
        
        JPanel totalPanel = new JPanel();
        totalPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));
        
        JLabel total =  new JLabel(Double.toString(cart.getTotalPrice()));
        
        totalPanel.add(total);
        
        mainPanel.add(invoice);
        mainPanel.add(totalPanel);
                

       frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       frame.add(topPanel, BorderLayout.NORTH);
       frame.add(mainPanel,BorderLayout.CENTER);
    //   frame.add(loginPanel, BorderLayout.CENTER);

       
       frame.setVisible(true);
   
       back.addActionListener(new ActionListener() 
       {

            @Override
            public void actionPerformed(ActionEvent ae)
            {
                frame.setVisible(false);
               ShoppingCartSystem.buyerPage.repaintTable();
            }
        });
       
       logout.addActionListener(new ActionListener() 
       {
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                frame.setVisible(false);
                ShoppingCartSystem.loginPage.display();
            }
        });
       
   } 
        
      
         private ShoppingCart cart;
}
